### ISSUE TITLE
[1.12] World state frozen (kinda) when quarry frame build crosses a TechGuns Ore Cluster block

### ISSUE THREAD

**Issue by b0bst3r** [Kotori316/QuarryPlus#117] opened 2021-05-17 19:23 UTC
**Describe the bug**
Breaks the world, mobs don't move/attack, most blocks are not interactable, blocks don't break, MC will not save, does not cause any crash, rather amusingly the day/night cycle still happens, you can still run around but the rest of the world is in a perpetual state of frozen.

**To Reproduce**
1. This is in a mod pack still in design phase and is a mod interaction with techguns ore clusters (an indestructible block).
2. Place down the quarry so the frame crosses a techguns ore cluster block
3. Wait until the frame draw gets to the ore cluster and bam world is frozen (kinda).

**Version**
* Minecraft: [1.12]
* Single Player or Multi Player?: [Single]
* Forge: [14.23.5.2847]
* This mod (QuarryPlus): [AdditionalEnchantedMiner-1.12.2-12.4.5-universal]
* Other mods: [techguns-1.12.2-2.0.2.0_pre3.2]
* 133 mods in total https://pastebin.ubuntu.com/p/gx68F5jFN4/

This breaks the world, the block it stopped at is the TechGuns OreCluster, I quit MC and it rolled back which gave me the opportunity to go into creative and break the ore cluster block to see if that was the issue.   Upon breaking the block in creative it fixed the problem.

![unknown](https://user-images.githubusercontent.com/2760085/118543816-af37cf80-b74c-11eb-913f-e73ec8db0550.png)

Edit: I don't know how you can fix this other than not allowing the quarry to work (message in GUI) if it detects an ore cluster block within the frame area.

**Comment by Kotori316** [comment] 2021-05-18 02:39
Sorry for that inconvenience.

It seems quarry fell into an infinite loop in server world. (Quarries or other machines work only in server world, that's why the sun continued moving in client world after no objects can be interacted.) It might be due to special way of quarry to break block and gather drops, or the special function of Ore Cluster from TechGun. The name "Ore Cluster" implies that you can get 2 or more ore drops from one block. The block won't be removed if you try to break with pickaxe (It's my imagination). This function might cause this frozen.

Anyway, I don't have the correct reason of this problem. I'll find what happened to the server world in my environment.
I'm afraid it will take a week or more because I'm a bit busy now. I will work on this problem on this weekend. I'm sorry for that.

**Comment by b0bst3r** [comment] 2021-05-18 04:34
The ore cluster block is not breakable, it's indestructible, it's present to be mined by a techguns miner machine, it's basically very slow infinite mining.  But yeah being indestructible like bedrock is probably the reason for the problem.

**Comment by Kotori316** [comment] 2021-05-20 13:16
Fixed in v12.4.7
It was a problem caused by insufficient treatment of unbreakable blocks including Bedrock in vanilla.
I installed TechGun and find that the quarry works fine now.

**Closed as completed by Kotori316** 2021-05-20 13:16 UTC
Labels: bug

**Comment by b0bst3r** [comment] 2021-05-20 18:54
Just a query then, if like when I found this the unbreakable block is in the frame area what happens does it just ignore the block and carry on or will it stop the quarry from working and it need repositioning?

**Comment by Kotori316** [comment] 2021-05-21 00:08
The unbreakable blocks are just ignored. Quarry will continue working.

>
>
