### ISSUE TITLE
Quarry does not mine dirt and clay

### ISSUE THREAD

**Issue by nalilord** [Kotori316/QuarryPlus#121] opened 2021-07-13 14:22 UTC
Hey,

I'm hosting a server for friends and there seems to be a problem with the QuarryPlus, the quarry is spitting out bees instead of dirt/clay, all other blocks seems to be fine. The OG BuildCraft quarry works correctly.

![image_2021-07-13_161832](https://user-images.githubusercontent.com/3942265/125468230-7454d74f-6f28-4628-91c3-faa780e4a297.png)

**Version**
* Minecraft: 1.12.2
* Single Player or Multi Player?: MP
* Forge: 14.23.5.2854
* This mod (QuarryPlus): 12.5.1
* Other mods: Enigmatica 2 - E2 Pack

**Comment by Kotori316** [comment] 2021-07-13 15:10
I'm sorry I don't have any idea of this problem. In my dev world with a few mods, dirt and clay are successfully collected as items.
Could you check the problem is still happened in new single player world?

**Comment by nalilord** [comment] 2021-07-13 18:56
Unfortunately no difference, tested it in SP in the mining world and overworld.

**Comment by nalilord** [comment] 2021-07-16 09:05
Just an update, I tested mod by mod when this occurs and it looks like it happens as soon as Ex Nihilo: Creatio is added.

**Comment by Kotori316** [comment] 2021-07-28 01:22
OK. Ex Nihilo: Creatio is doing something that will convert dirt to bees. I'll check what happens in the break loops.
I think you can silktouch quarry to avoid this issue. Ex Nihilo: Creatio doesn't do such conversion if the dirt is removed with Silktouch.

**Comment by Kotori316** [comment] 2021-07-28 01:24
Oh, I found Quarry Pickaxe is registered as Crook. Definitely it's the problem. I'll add exception setting for Crooks.

**Comment by Kotori316** [comment] 2021-07-29 07:13
Fixed in v12.5.4

**Closed as completed by Kotori316** 2021-07-29 07:13 UTC
Labels: bug
