### ISSUE TITLE
[1.12.2] Quarry Plus bug stoped Java

### ISSUE THREAD

**Issue by sirohigan** [Kotori316/QuarryPlus#40] opened 2018-12-09 13:58 UTC
When I send energy with an obstacle in the building range of QuarryPlus frame, all machines are stopped.
When I try to quit Minecraft in this state, the Java Platform will stop. LoiLo recorder using Java was also stopped.
Since Java is down, no crash reports are generated.
Is it possible to fix it?

・Recording
https://youtu.be/vt3PcR_VNjw

・Introduced MOD
Java：re1.8.0_181
1.12.2-forge1.12.2-14.23.4.2766
AdditionalEnchantedMiner-1.12.2-0.10.4-universal
appliedenergistics2-rv6-stable-1
ExtraCells-1.12.2-2.6.1a
EnderCore-1.12.2-0.5.43
EnderIO-1.12.2-5.0.37
MCMultiPart-2.5.3
Mekanism-1.12.2-9.4.13.349
MekanismGenerators-1.12.2-9.4.13.349
MekanismTools-1.12.2-9.4.13.349

**Comment by Kotori316** [comment] 2018-12-09 23:53
Duplicate of #38.

Thank you for your report and details.
I got the same issue and uploaded fixed version [0.10.5](https://github.com/Kotori316/QuarryPlus/releases/tag/v0.10.5-1.12.2).
Try it and tell me if the infinite loop is fixed. (The stop is due to infinite loop in QuarryPlus.)

**Comment by sirohigan** [comment] 2018-12-10 10:37
Thank you.
Its succeeded.
I will use it.

**Closed as completed** 2018-12-10 15:36 UTC
Labels: bug, duplicate
