### ISSUE TITLE
Something odd with the chunk destroyer 

### ISSUE THREAD

**Issue by Milii20** [Kotori316/QuarryPlus#36] opened 2018-11-18 16:17 UTC
Greetings, i updated from 0.9.22 to 0.10.0, and my chunk destroyer started doing this weird pattern instead of digging the entire chunk

![2018-11-18_13 13 45](https://user-images.githubusercontent.com/10578092/48675152-4861dd00-eb34-11e8-8145-f0c017b84c50.png)

(For some context: on the Aroma mining world, but i already tried even on the overworld and had the same results, going back to 0.9.22 aparently fixes it)

**Comment by Kotori316** [comment] 2018-11-26 06:10
I can't reproduce your problem...
What are you using as energy source? How many RF/t does it send?

Anyway, I rewrote codes and changed some logic in [0.10.1](https://minecraft.curseforge.com/projects/additional-enchanted-miner/files/2641492). Try it.

**Comment by Milii20** [comment] 2018-11-26 20:44
As power source i was using two, first a solar panel tier 6 from environmental tech connected via Thermal Dynamics Cryoducts to the chunk destroyer (arround 1.7 million RF/t), which was later changed for overloaded's creative generator, which outputs 2.1 billion RF/t per side, directly placed next to the chunk destroyer.

i forgot to mention one thing, the chunk destroyer behaved normally in a 32x32 chunk square, but the one in the picture was way bigger, being (i think) 1024x1024 chunk square, 0.10.0 made that pattern, but 0.9.22 worked with those huge distances

**Comment by Milii20** [comment] 2018-11-26 22:56
my reports on 0.10.1, found another problem, maybe i am messing something up, since i cannot record minecraft for some reason i will just post images detailing the new problem

first: i have a chunk destroyer, made a non enchanted one for reference, but both work the same way
![2018-11-26_19 37 33](https://user-images.githubusercontent.com/10578092/49046474-00d1f580-f1b3-11e8-8755-c78632c5aedd.png)


then, i place said chunk destroyer, the chunk borders apear, detailing  only 1 chunk
![2018-11-26_19 37 36](https://user-images.githubusercontent.com/10578092/49046497-1b0bd380-f1b3-11e8-9e86-c402258b0465.png)

But, when i try to access the chunk destroyer to change the size, this happens, please notice the chunk lines disapeared, no numbers are visible, and the + and - do nothing on any of the coordinates
![2018-11-26_19 37 38](https://user-images.githubusercontent.com/10578092/49046543-45f62780-f1b3-11e8-8bc8-c05e98a7842b.png)


i close the gui, and stays the same
![2018-11-26_19 37 39](https://user-images.githubusercontent.com/10578092/49046569-5908f780-f1b3-11e8-9188-cfc57a9e340c.png)

after that, i give it power and it starts to mine only the chunk the destroyer was on
![2018-11-26_19 41 10](https://user-images.githubusercontent.com/10578092/49046623-8655a580-f1b3-11e8-914b-a8b983488536.png)

(i know i am using a resource pack, but i already tried without one too, same resoults)
![2018-11-26_19 49 31](https://user-images.githubusercontent.com/10578092/49046991-cb2e0c00-f1b4-11e8-8f38-00e241036455.png)

here is my mods list, maybe i am not seeing something

[modlist](https://pastebin.com/RhmA504x)

**Comment by Kotori316** [comment] 2018-11-28 03:23
This range bug is due to nbt saving and loading, and fixed in eef6a955be38b922e0accd8d3ce16ba1d99ca8d0.
I'll build jar file and upload 0.10.2 in some hours.

ADDED:
Uploaded. ~[Download from here](https://minecraft.curseforge.com/projects/additional-enchanted-miner/files/2642140)~

ADDED2:
Uploaded 0.10.3, which I checked the machine digs 64x64 chunks as 0.9.22 does.
[Download](https://minecraft.curseforge.com/projects/additional-enchanted-miner/files/2642148)

**Comment by Milii20** [comment] 2018-11-28 23:13
0.10.3 works like a charm, thank you so much for fixing it so fast! (tested on 256x256 and no weird pattern!)

**Closed as completed** 2018-11-30 04:19 UTC
Labels: bug
